  import type { Metadata } from "next";
  import { Georama } from "next/font/google";
  import { Monsieur_La_Doulaise,Outfit } from "next/font/google";
  import "./globals.css";
  import LayoutWrapper from "./componets/layoutwrapper";
  const georamaMono = Georama({
    variable: "--font-georama-mono",
    weight:"300",
    subsets: ["latin"],
    display: "swap",
  });

  const OutfitMono=Outfit({
    variable:"--font-outfit",
    weight:"400",
    subsets:["latin"],
    display:"swap"
  })

  const Monsieur_La_DoulaiseMono=Monsieur_La_Doulaise({
      variable: "--font-Monsieur",
      weight: "400",
      subsets: ["latin"],
      display: "swap",
  })
  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

  export default function RootLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
    return (
      <html lang="en">
        <body
          className={`${Monsieur_La_DoulaiseMono.variable} antialiased`}
        >
          
          <LayoutWrapper>{children}</LayoutWrapper>
        </body>
      </html>
    );
  }
